[workspace]
authors = ["avcopan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "proj-c5-species-o2-sweeps"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
cantera = ">=3.2.0,<4"
polars = ">=1.38.1,<2"
altair-all = ">=6.0.0,<7"
numpy = ">=2.4.2,<3"
ipykernel = ">=7.2.0,<8"
